server:
  port: 8082

spring:
  application:
    name: ProductService
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productDB
sleuth:
  sampler:
    probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



