server:
  port: 8087

spring:
  application:
    name: ProductService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productServiceDB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  file:
    path: /Users/m80007278/Documents/loggings

