server:
  port: 8081

spring:
  application:
    name: ProductService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productDB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

